# Generated by Django 2.2.2 on 2019-06-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration_in_month',
            field=models.SmallIntegerField(),
        ),
    ]
