# Generated by Django 2.2.2 on 2019-08-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20190627_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration_in_month',
            field=models.IntegerField(),
        ),
    ]
